CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230710164845_InitialCreate') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'moleculesapp') THEN
            CREATE SCHEMA moleculesapp;
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230710164845_InitialCreate') THEN
    CREATE TABLE moleculesapp."CalcOrder" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(250) NOT NULL,
        "Description" text NOT NULL,
        "CustomerName" text NOT NULL,
        CONSTRAINT "PK_CalcOrder" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230710164845_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20230710164845_InitialCreate', '7.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230711080702_AddCalcOrderItemDbEntity') THEN
    CREATE TABLE moleculesapp."CalcOrderItem" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "MoleculeName" character varying(250) NOT NULL,
        "Charge" integer NOT NULL,
        "CalcType" character varying(50) NOT NULL,
        "XYZ" text NOT NULL,
        "CalcOrderId" integer NOT NULL,
        CONSTRAINT "PK_CalcOrderItem" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_CalcOrderItem_CalcOrder_CalcOrderId" FOREIGN KEY ("CalcOrderId") REFERENCES moleculesapp."CalcOrder" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230711080702_AddCalcOrderItemDbEntity') THEN
    CREATE INDEX "IX_CalcOrderItem_CalcOrderId" ON moleculesapp."CalcOrderItem" ("CalcOrderId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230711080702_AddCalcOrderItemDbEntity') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20230711080702_AddCalcOrderItemDbEntity', '7.0.8');
    END IF;
END $EF$;
COMMIT;

